### ISSUE TITLE
gem oauth2

### ISSUE THREAD

**Issue by lenarakhmadeev** [nononoy/bitrix24_cloud_api#1]
При подключении к Rails 4, по всей видимости, нужно предварительно подключить oauth2. Возможно, стоит подключить эту зависимость внутри гема?

```
gem 'oauth2'
gem 'bitrix24_cloud_api'
```

**Comment by nononoy** [comment]
oauth2 включен в bitrix24_cloud_api.gemspec development_dependencies. Какие-то проблемы в его работе?

**Comment by lenarakhmadeev** [comment]
Ставлю гем 'bitrix24_cloud_api' в приложение, а 'oauth2' не ставится.
По всей видимости, нужно add_dependency вместо add_development_dependency.
Сделал ПР #2

**Comment by nononoy** [comment]
обновил runtime зависимости

**Comment by lenarakhmadeev** [comment]
Спасибо
