### ISSUE TITLE
Connection refused - connect(2) for nil port 443

### ISSUE THREAD

**Issue by dmigous** [nononoy/bitrix24_cloud_api#5]
Сделал все по инструкции в README

получаю такую ошибку:

```
2.2.2 :056 > Bitrix24CloudApi::CRM::Lead.list(@client)
Errno::ECONNREFUSED: Connection refused - connect(2) for nil port 443
```

Выполняю команды из `rails c` (но `code` присваиваю и делаю вызов  `access_token = @client.get_access_token(code)` точно в течении 30 секунд).

Тестирую на локальной машине.

**Comment by nononoy** [comment]
Если это все данные при создании @client, то их явно мало. Вот примерные параметры:

```
params = { 
  endpoint: api_endpoint,
  scope: [:crm, :user],
  redirect_uri: "https://#{api_endpoint}",
  client_id: xxx,
  client_secret: xxx
}
Bitrix24CloudApi::Client.new(params)
```

Раз падает на 443 порту, значит порт не задействован.

**Comment by dmigous** [comment]
Я создаю все как в README, вот такие параметры.
```
  	params = { 
  		endpoint: "wooХХoХХХ.bitrix24.ua",
	    client_id: 'local.ХХХХХХХХХХХХХХ.ХХХХХХХ',
	    client_secret: 'TE1HvX97A2OdVQХХХХХХХХХХХХХХХХХХХХХХХХХHSL32T8B',
	    scope: "crm",
	    extension: "json",
	    redirect_uri: "https://wooХХoХХХ.bitrix24.ua"
	}
	@client = Bitrix24CloudApi::Client.new(params)
```

> Раз падает на 443 порту, значит порт не задействован.

как его задействовать? Bitrix API работает только через https?

**Comment by nononoy** [comment]
Получение токенов происходит? Выдает access_token? Опубликуйте полный backtrace ошибки.

После получения access_token параметры должны быть следующие(возможно вы не передаете endpoint):
```
params = { 
   endpoint:  api_endpoint,
   access_token:  access_token,
   scope: [:user, :crm]
}
```

**Comment by dmigous** [comment]
да, я делаю так

```
@client = Bitrix24CloudApi::Client.new(access_token: access_token)
```

**Comment by nononoy** [comment]
Видимо, пора привести в порядок Readme.md. Пробуйте передавать endpoint.

```
params = { 
   endpoint:  api_endpoint,
   access_token:  access_token,
   scope: [:user, :crm]
}
@client = Bitrix24CloudApi::Client.new(params)
```

**Comment by dmigous** [comment]
А access_token в params это результат `access_token = @client.refresh_token(refresh_token)` или `access_token['access_token']` ?

**Comment by nononoy** [comment]
Если токен еще не истек, то access_token['access_token']. Если истек - рефрешите его и передаете опять access_token['access_token'], только уже обновленный.

**Comment by dmigous** [comment]
сработало, спасибо!

FYI, нужно было access_token[:access_token] (ключ как символ)
