### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Serhii-Danovsky** [nononoy/bitrix24_cloud_api#7]
To get oauth2 authorize_url for code simple use:

authorize_url = @client.authorize_url
To get oauth2 access_token use:

access_token = @client.get_access_token(code)
it's response contains a hash with oauth2 credentials and some other usefull data.

To refresh oauth2 access_token use:

access_token = @client.refresh_token(refresh_token)

Подскажите пожалуйста что за code и где его взять

**Comment by nononoy** [comment]
Перейти по ссылке authorize_url, в ответ сгенерится code

**Comment by Serhii-Danovsky** [comment]
У меня постоянно
`{"error"=>"NO_AUTH_FOUND", "error_description"=>"Wrong authorization data", :code=>401}
`
А можно Вас попросить сделать пример ?
обязательно ли omniauth 2 ?
У меня простое задние:
 при создании юзера делать:
```
param = { fields: {TITLE: "title", PHONE: [VALUE: "123", VALUE_TYPE: "WORK"]} }
Bitrix24CloudApi::CRM::Lead.add(@client, param)
```
Возможно ли это сделать при помощи Вашего гема , в контроллере без участия пользователя ?

Код : local.5b2a4234b25ba4.26470483
Ключ : si3MpX1KaGgAF078yX9Xyl2OXY66LwVfaxiSzdjR5e2PIxBbSX

**Comment by nononoy** [comment]
Нельзя без oauth2 и редиректа. 

```
params = { 
  endpoint: {url_bitrix24},
  scope: [:crm, :user],
  redirect_uri: {url_bitrix24},
  extension: "json",
  client_id: 'local.5b2a4234b25ba4.26470483',
  client_secret: 'si3MpX1KaGgAF078yX9Xyl2OXY66LwVfaxiSzdjR5e2PIxBbSX'
}
client = B24::Client.new(params)   
  
authorize_url = client.authorize_url
```
client_id и client_secret берутся из приложения для маркетплейса битрикса. 

Битрикс24 должен быть на протоколе https (не http). Для работы с REST API в коробке должен быть установлен модуль REST API (Настройки - Настройки продукта - Модули). Обновление Интранет не ниже 16.6.4.

**Comment by Serhii-Danovsky** [comment]
Спасибо большое.
Оказалось все гораздо проще.
Реализовал добавление лидов через  Входящие вебхуки. 
Там нужно только *код для авторизации вебхука в Битрикс24* 
Без oauth2

**Comment by nononoy** [comment]
Там только создание лидов, если не ошибаюсь. Редактировать и прочее не получится

**Comment by Serhii-Danovsky** [comment]
crm.lead.update  и crm.lead.delete  - работают , только что проверил в postman
